### ISSUE TITLE
Out of order scanning

### ISSUE THREAD

**Issue by OverkillGuy** [OverkillGuy/qrxfil#13]
Current naive implementation does not support chunks that are not properly sorted.

Let's write a test that shows this doesn't currently work and solve it.

This ticket does not include managing missing-chunk logic, which is #14.

**Comment by danieleades** [comment]
`BTreeMap` is probably your friend here

**Comment by OverkillGuy** [comment]
Ugh. 70004d9 was supposed to close this ticket, solved.
